### ISSUE TITLE
Port 80 und 5060 sind nicht freigegeben

### ISSUE THREAD

**Issue by Prendeon** [fastplayer95/GotV-Network#23]
Wir benötigen für die Installationsphase Zugriff vom hda-Netzwerk auf die Servermodule über Port 80 und 5060.

**Comment by fastplayer95** [comment]
Zugriff auf die Ports solltest du haben, zumindest aus dem FBI-Netz.

Wenn der Server dir unter den genannten Ports Dienste bereitstellt, solltest du diese auch entsprechend nutzen können.

Siehe: 141.100.71.125/haproxy?stat 
Webserver ist über Standardport 80 erreichbar
