### ISSUE TITLE
Sammeln von Infos über Server

### ISSUE THREAD

**Issue by fastplayer95** [fastplayer95/GotV-Network#5]
Wir benötigen Infos über die benötigte Peformance

**Comment by MarcSchaefer** [comment]
das sind die mindest Anforderungen für Gruppe "Verteidigung 1":
Intel Xeon e7-4809 v3 (20M Cache, 2.0 GHz) 
32GB RAM (wahlweise 64GB)
500GB SATA HDD
Network: 1Gbit / 10Gbit
Betriebssystem: Debian 8.5 Jessie

**Comment by fastplayer95** [comment]
@MarcSchaefer SIP-Proxy oder SBC?

**Comment by fastplayer95** [comment]
Ergebnisse werden heute an Sergio weitergegeben => Closed

**Comment by fastplayer95** [comment]
Aufgrund der Virtualisierung werden die VM's anfangs etwas geringer ausgestattet sein als in den Anforderungen festgelegt wurde.
Wird tatsächlich mehr Leistung benötigt, werden die zu Verfügung stehenden Ressourcen entsprechend skalliert.
