### ISSUE TITLE
Banana pis

### ISSUE THREAD

**Issue by boisjacques** [fastplayer95/GotV-Network#8]
Hallo,

wir haben keine Rückmeldung zu den Babana Pis gegeben, da wir davon ausgingen, dass diese wie in eurer Präsentation geplant beschafft werden, nachdem wir die Eignung von Banana Pis in der Whatsapp Gruppe nochmal bestätigt haben. Bitte das Banana Pi Array (in Rücksprache mit uns alternativ auch einen Server) weiterhin einplanen.

Gruß
Manu

**Comment by fastplayer95** [comment]
Auf die Info, dass Raum D14 3.04 mit mehr als 10Gbit angebunden ist werden wir Angebote für 10 Banana Pi's einholen #11

**Comment by boisjacques** [comment]
Okay, super.
